### ISSUE TITLE
Build takes 20 minutes on travis

### ISSUE THREAD

**Issue by markfuller** [lyraproj/lyra#107]
Example link https://travis-ci.org/lyraproj/lyra/builds/488962500?utm_source=github_status&utm_medium=notification

make takes 1140.27s (i.e. just shy of 20 minutes)

Probably the time is spent downloading packages.

Explore caching in travis? https://docs.travis-ci.com/user/caching/

**Comment by kenazk** [comment]
https://twitter.com/ahmetb/status/1092849975745077248

Computer just started to take off when compiling.

**Comment by scottyw** [comment]
We enabled caching and made build improvements. Most recent build on Travis is 14 mins. The actual build is 8.5 mins of that, the rest being Travis stuff like setup and cache persistence I think. Our local builds are a lot faster now, typically 45s to 60s.

Do you think we can close this ticket? I'm not sure what else we can do.
