### ISSUE TITLE
Produce Lyra builds (via Travis)

### ISSUE THREAD

**Issue by jdwelch** [lyraproj/lyra#12]
Enable and configure Travis to build (and optionally store) builds of Lyra for Linux and macOS

**Comment by jdwelch** [comment]
#26

**Comment by ahpook** [comment]
I'm gonna remove this from 0.1 - but we do need to come up with a packaging/release strategy.

**Comment by scottyw** [comment]
In #242 we're changing the `build` dir structure to support this work:
```
build
 └─ bin
     └─ lyra
 └─ goplugins
     └─ aws
     └─ puppetdsl
     └─ ...
```

That aligns with the separation of `bin` from `plugins` that we're looking for in `brew`. We also need `workflows` and `types`. Ultimately the brew installation should look like this:
```
lyra/0.0.1
 └─ bin
     └─ lyra
 └─ goplugins
     └─ aws
     └─ puppetdsl
     └─ ...
 └─ workflows
     └─ aws_pp.pp
     └─ aws.yaml
     └─ ...
 └─ types
     └─ aws.pp
     └─ ...
```
