### ISSUE TITLE
Include i18n externalized strings in the binary

### ISSUE THREAD

**Issue by scottyw** [lyraproj/lyra#150]
**Is your feature request related to a problem? Please describe.**
Our binary does not include any of our externalized strings and depends on them being at a certain relative path. This means it is easy to run the binary and find none of the UI strings present e.g.
```
~/github/lyra/build ᐅ ./lyra
 _
| |
| |    _   _ _ __ __ _
| |   | | | | '__/ _` |
| |___| |_| | | | (_| |
\_____/\__, |_|  \__,_|
        __/ |
       |___/

Description:
  rootCmdLong

Usage:
  rootCmdUse [flags]

Available Commands:
  applyCmdUse    applyCmdShort
  controller     controllerCmdShort
  deleteCmdUse   deleteCmdShort
  generateCmdUse generateCmdShort
  validateCmdUse validateCmdShort
  versionCmdUse  versionCmdShort

Flags:
      --debug             rootFlagDebug
  -h, --help              help for rootCmdUse
      --loglevel string   rootFlagLoglevel
      --version           version for rootCmdUse
```
**Describe the solution you'd like**
All (or at least one set of) strings present in binary. This can probably best be achieved using `go generate` and https://github.com/kevinburke/go-bindata.

**Comment by jdwelch** [comment]
Oh yikes, yeah that's terrible.

**Comment by scottyw** [comment]
Easy fix though so I think we're cool.

**Comment by scottyw** [comment]
Closed by https://github.com/lyraproj/lyra/pull/156
