### ISSUE TITLE
Offer a means to indicate that fields of nested types are provided/immutable

### ISSUE THREAD

**Issue by scottyw** [lyraproj/lyra#161]
When registering a type with the service-sdk, all nested complex types will also be registered automatically. For example given this `Aws_acm_certificate` type, the nested `Aws_acm_certificate_domain_validation_options_1` type will also be registered:
```go
type Aws_acm_certificate struct {
    ...
    Domain_validation_options *[]Aws_acm_certificate_domain_validation_options_1
    ...
}
```

It is also possible to specify certain attributes as `provided` or `immutable` when registering a type using a `ResourceTypeBuilder` func like this:

```go
var Aws_acm_certificate_rtb = func(rtb service.ResourceTypeBuilder) {
	rtb.ProvidedAttributes("domain_name")
	rtb.ImmutableAttributes("subject_alternative_names")
}
```
 ... which is supplied at registration time like this:

```go
evs = sb.RegisterTypes("TerraformAws", 
    sb.BuildResource(&Aws_acm_certificate{}, 
    Aws_acm_certificate_rtb))
```

To specify fields within the nested types as `provided` or `immutable`, it's possible to add an additional `sb.BuildResource()` with annotations for the nested type that that precedes the one for the container of that nested type. That annotation will not be considered by the comparison algorithm later on.

@thallgren, @markfuller and I discussed the possibility of using struct field metadata tags to address this, which would solve the problem in cases where we have control over the source code for the nested types e.g. in our generated bridge providers.
```go
type Aws_acm_certificate_domain_validation_options_1 struct {
    Domain_name *string `lyra:"immutable,provided"`
    Resource_record_name *string `lyra:"immutable"`
    Resource_record_type *string
    Resource_record_value *string
}
```
It's not clear what we might do if we don't have control over the source, or how much of the problem that is.

**Comment by thallgren** [comment]
@scott wrote: "However, it is not currently possible to specify fields within the nested types as provided or immutable". This is a modified truth. You should be able do that, by adding an additional `sb.BuildResource()` with annotations for the nested type that that precedes the one for the container of that nested type. But even if you do, that annotation will not be considered by the comparison algorithm later on.

I think we have two options. One is to improve the `RegisterTypes` to accept additional semantics to declare annotations on nested types, or we consider that part good enough as it is with the inconvenience that the nested type must precede its container. In any case, the comparison algorithm must be improved.

**Comment by scottyw** [comment]
Sorry! I edited the description to correct the mistake.
