### ISSUE TITLE
Travis CI for other lyraproj repos (other than lyraproj/lyra which already has it) 

### ISSUE THREAD

**Issue by markfuller** [lyraproj/lyra#187]
**Is your feature request related to a problem? Please describe.**
Run CI (test/lint) on various lyraproj projects not yet covered.

**Describe the solution you'd like**
Tests and linting to match lyraproj/lyra

**Describe alternatives you've considered**
N/A

**Additional context**
Check how travis is rate limited and check no impact there.

**Comment by markfuller** [comment]
To add travis to a repo
* go to , sign in and navigate to settings in top right
* Should take you to https://travis-ci.org/account/repositories
* Select lyraproj organization
* (assume must be owner of https://github.com/lyraproj and have sync-ed in travis via "sync organization)
* Should take you to https://travis-ci.org/organizations/lyraproj/repositories
* Toggle repos on and off as per image below
* Add .travis.yml in a PR

![image](https://user-images.githubusercontent.com/13329288/55110363-c8deae80-50cf-11e9-83cd-6100f109d251.png)

**Comment by jdwelch** [comment]
Where do the results end up? Maybe do those [fancy badge things](https://docs.travis-ci.com/user/status-images/) on each repo?

**Comment by markfuller** [comment]
https://www.traviscistatus.com/

>>> We are seeing an increase in the build backlog and we are looking into it. Thank you for your patience.

**Comment by markfuller** [comment]
> Where do the results end up? Maybe do those [fancy badge things](https://docs.travis-ci.com/user/status-images/) on each repo?

Also on the PR page itself https://github.com/lyraproj/pcore/pull/4

![image](https://user-images.githubusercontent.com/13329288/55148779-c7010380-5140-11e9-9176-01a91521c819.png)

**Comment by jdwelch** [comment]
oh, right, of course 🤦‍♂️

**Comment by markfuller** [comment]
This work is complete.
