### ISSUE TITLE
Produce consistent versions of existing workflow examples

### ISSUE THREAD

**Issue by markfuller** [lyraproj/lyra#188]
**Is your feature request related to a problem? Please describe.**
We need all examples that are currently in one language (yaml/puppet/ts) to be present in the others where possible so that we can point people towards yaml for the most straightforward examples, and typescript for more advanced examples.

Ideally, include an imperative step in the TS examples.

**Describe the solution you'd like**
* Typescript examples to match yaml/puppet
* Updated readme to point people towards yaml and then typescript for more advanced cases.
* Consider running a TS sample in the build.

**Describe alternatives you've considered**
N/A

**Additional context**
Yaml is the dominant language in this space, but is somewhat limited for our usage e.g. functions, imperative steps.  Here, Typescript allows richer examples more naturally than yaml.  As per #91 we would like to limit the promotion of puppet DSL. 

**Progress**
@markfuller and I worked through the existing examples which contain a bunch of duplication and variants on content. We're planning to remove duplication and make sure all examples are implemented in all supported languages (where possible).

The plan is to end up with the following examples:

- **AWS ("native" content):** Remove examples in preference to TF content
- **AWS (TF content):** instance / internetgateway / routetable / vpc / securitygroup / subnet / keypair / iam role
  - [x] yaml
  - [x] ts
  - [x] puppet
- **Azure:** resource group / virtual network / subnet / public IP / network security group / network interface / virtual machine
  - [x] yaml
  - [x] ts
  - [ ] puppet
- **GCP:** compute instance / other TBD networking resources similar to Azure/AWS
  - [x] yaml
  - [x] ts
  - [ ] puppet
- **GitHub:** repo
  - [x] yaml
  - [x] ts
  - [ ] puppet
- **Kubernetes:** namespace / service
  - [x] yaml
  - [x] ts
  - [x] puppet
- **Basic illustrative sample:** perhaps showing 3 resources with dependent relationships
  - [x] yaml
  - [x] ts
  - [x] puppet
- **Intermediate illustrative sample:** extending basic to include many resources, actions, lookup, aliasing, maybe more?
  - [x] yaml
  - [x] ts
  - [x] puppet
- **Complete illustrative sample:** all Lyra syntax captured in a single workflow
  - [x] yaml
  - [x] ts
  - [x] puppet

**Comment by scottyw** [comment]
@markfuller and I worked through the existing examples which contain a bunch of duplication and variants on content. We're planning to remove duplication and make sure all examples are implemented in all supported languages (where possible).

The plan is to end up with the following examples:

- **AWS ("native" content):** instance / internetgateway / routetable / vpc / securitygroup / subnet / keypair / iam role
  - [ ] yaml
  - [ ] ts
  - [ ] puppet
- **AWS (TF content):** same as above, just different content
  - [ ] yaml
  - [ ] ts
  - [ ] puppet
- **Azure:** resource group / virtual network / subnet / public IP / network security group / network interface / virtual machine
  - [ ] yaml
  - [ ] ts
  - [ ] puppet
- **GCP:** compute instance / other TBD networking resources similar to Azure/AWS
  - [ ] yaml
  - [ ] ts
  - [ ] puppet
- **GitHub:** repo
  - [ ] yaml
  - [ ] ts
  - [ ] puppet
- **Kubernetes:** namespace / service
  - [ ] yaml
  - [ ] ts
  - [ ] puppet
- **Basic illustrative sample:** perhaps showing 3 resources with dependent relationships
  - [ ] yaml
  - [ ] ts
  - [ ] puppet
- **Intermediate illustrative sample:** extending basic to include many resources, actions, lookup, aliasing, maybe more?
  - [ ] yaml
  - [ ] ts
  - [ ] puppet
- **Complete illustrative sample:** all Lyra syntax captured in a single workflow
  - [ ] yaml
  - [ ] ts
  - [ ] puppet
