### ISSUE TITLE
TF bridge plugin generation should use deterministic suffixes

### ISSUE THREAD

**Issue by scottyw** [lyraproj/lyra#197]
**Describe the bug**
The TF plugin generator uses an incrementing integer as a suffix for generated types to ensure uniqueness e.g. "Azurerm_network_security_group_security_rule_164".

As the Azure provider changes, the suffix attached to a given resource type will change e.g. "Azurerm_network_security_group_security_rule_164" might become "Azurerm_network_security_group_security_rule_165". That breaks all existing workflows.

**Expected behavior**
Two options here:
* Resolve #66 so that generation is removed completely and this problem just goes away
* Use a deterministic suffix / name e.g. a hash of the parent hierarchy of the type

**Comment by thallgren** [comment]
I have a solution for this in the work that I'm currently doing on the TF-bridge.

**Comment by thallgren** [comment]
Fixed by lyraproj/terraform-bridge#2.
