### ISSUE TITLE
Log level is not passed correctly to plugins

### ISSUE THREAD

**Issue by markfuller** [lyraproj/lyra#200]
**Is your feature request related to a problem? Please describe.**
When running something like `build/lyra apply sample --debug`, the log level (debug) is not (successfully) passed to the plugin.

**Describe the solution you'd like**
Remove `--debug` in favor of `--logLevel fatal|error|warn|info|debug|trace` (this is already partially or fully implemented)

Ensure that log level is passed to the plugin.  We might be missing something out of the box with hclog - [we do pass a logger to the plugin](https://github.com/lyraproj/servicesdk/blob/535e2bee62c533666df2a4b4b927bca241b51686/grpc/client.go#L93-L103).

Alternately some prior art [here](https://github.com/markfuller/lyra/commits/logging-in-plugin), though this is out of date following #181

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jdwelch** [comment]
See also #110 I think?

**Comment by scottyw** [comment]
PR #217
