### ISSUE TITLE
Investigate how we might infer the need to "delete before create"

### ISSUE THREAD

**Issue by scottyw** [lyraproj/lyra#203]
**Describe the bug**
When Lyra needs to delete and recreate a resource, it creates the new resource first and garbage collects the old resource at the end of the run. That's a deliberate choice to help avoid dependency errors on deletion as described in #160. 

There are some cases where that doesn't work e.g. AWS key pairs.

**To Reproduce**

Take this workflow:

```yaml
aws:
  typespace: TerraformAws
  activities:
    aws_key_pair:
      state:
        key_name: lyra-test-keypair
        public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCX363gh/q6DGSL963/LlYcILkYKtEjrq5Ze4gr1BJdY0pqLMIKFt/VMJ5UTyx85N4Chjb/jEQhZzlWGC1SMsXOQ+EnY72fYrpOV0wZ4VraxZAz3WASikEglHJYALTQtsL8RGPxlBhIv0HpgevBkDlHvR+QGFaEQCaUhXCWDtLWYw== nyx-test-keypair-nopassword"
```

If run twice the following errors occurs, because it is not possible to create two keys pairs with the same name. 

```
2019-03-28T14:08:01.939Z [DEBUG] lyra.terraformaws: 2019-03-28T14:08:01.939Z [ERROR] Invoke failed: error="Go function Create returned error 'Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'lyra-test-keypair' already exists.
2019-03-28T14:08:01.939Z [DEBUG] lyra.terraformaws: 	status code: 400, request id: 29ad2b5f-d346-4739-ae7a-217222265655' (file: /Users/scott/go/pkg/mod/github.com/lyraproj/pcore@v0.0.0-20190320221415-6e1d1bd9c47d/types/function.go, line: 104)"
invocation of TerraformAws::Aws_key_pairHandler create failed: PCORE_GO_FUNCTION_ERROR Go function Create returned error 'Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'lyra-test-keypair' already exists.
	status code: 400, request id: 29ad2b5f-d346-4739-ae7a-217222265655' (file: /Users/scott/go/pkg/mod/github.com/lyraproj/pcore@v0.0.0-20190320221415-6e1d1bd9c47d/types/function.go, line: 104)
```

See also #52, which focuses on what Lyra should do when existing resources are found, versus this ticket which focuses on use cases where late deletion doesn't work. 

**Expected behavior**
We can solve this problem with metadata but in the case of our bridged content that's not really a scalable solution.

It would be good to investigate whether we can find a heuristic that addresses both #160 and this issue. For example, could we first try "create before delete" but fall back to trying "delete before create" if the creation fails?

**Comment by scottyw** [comment]
@thallgren Would be great to get your take on this.

**Comment by thallgren** [comment]
My preference would be to always control things like this with metadata, even when we generate it. We could do so by providing a way to amend the generated types with knowledge that we cannot derive from the provider. I suspect that there will be other things that we will want to add later on.

I can add an API to the generator that will allow us to add annotations to the generated types by passing a map with such info.

I'm not a fan of enforcing a trial and error approach. I'm concerned that if we do, we lose on other important aspects, such as predictability and reproducibility. I also think that we might run into other use-cases where it's always desirable to delete first, even if it will work to defer the delete until GC.
