### ISSUE TITLE
Workflow with 2 AWS security groups fails due to identity service crash

### ISSUE THREAD

**Issue by scottyw** [lyraproj/lyra#244]
**Describe the bug**
@eglenfield discovered this issue where an identity service crash prevents successful application of a workflow with two AWS security groups.

Commenting out the second security group means the workflow can be successfully applied.

There are other commented out resources, like internet gateway, seem to cause similar problems.

I was able to recreate and removing the identity.db before run didn't fix the problem.

**To Reproduce**
Apply this workflow: [aws.yaml](https://github.com/lyraproj/lyra/files/3116387/workflow.txt)

The following stack trace results: [stacktrace.txt](https://github.com/lyraproj/lyra/files/3116389/stacktrace.txt)

**Comment by thallgren** [comment]
This is interesting. The stack contains several timeouts from the `Identity` service, and it's reproducible.
