### ISSUE TITLE
Improve list of dependencies required for installation 

### ISSUE THREAD

**Issue by jdub55** [lyraproj/lyra#255]
Downloaded Lyra and ran make. After getting through the download of all the dependent projects (15+ minutes on my mifi connection), I encountered this error:

🔘 Ensuring node version is 9.0.0 or later (12:31:31)
🔴 must be running Node version 9.0.0 or later.  Exiting
make: *** [check-node] Error 1

**Describe the solution you'd like**
Would be super helpful to do a dependency check up front or list in the docs what version of Node is required.

**Comment by markfuller** [comment]
👍 

Great point.  Because TypeScript and node.js are entirely optional for working with lyra, I propose #257 to clarify this and remove the TypeScript/node smoke tests from the default make target.
