### ISSUE TITLE
Update getting started documentation

### ISSUE THREAD

**Issue by jdwelch** [lyraproj/lyra#277]
Updates to the README or other docs would be really helpful for a novice user. Here are some things that struck me as missing on my last run through:

+ Something step-by-step about authoring workflows
+ Explain the difference between `examples/` and `workflows/`
+ Explain what an `.ll` file is and how to use it
+ Add a `workflow-ts.md` in docs/ simiar to the Puppet and YAML versions

**Comment by jdwelch** [comment]
cc @ahpook

**Comment by hestonhoffman** [comment]
Hi @jdwelch. I'm working on the first bit now. I've also written a couple a conceptual doc that I'll try to PR by the end of the week.

**Comment by jdwelch** [comment]
👍

**Comment by ahpook** [comment]
@hestonhoffman how are these updates coming? can you push up a WIP pull request even if it's not finalised?

**Comment by hestonhoffman** [comment]
@ahpook I opened a PR to move the docs to lyaproj/docs. I added an overview that's live at https://lyraproj.github.io/docs/. I'll have a WIP workflows doc up in the next couple days.

**Comment by ahpook** [comment]
Thanks @hestonhoffman !
