### ISSUE TITLE
terraform-bridge required list becomes Optional in lyra

### ISSUE THREAD

**Issue by markfuller** [lyraproj/lyra#279]
**Describe the bug**
The [terraform-bridge](https://github.com/lyraproj/terraform-bridge) seems to convert a `Required` `List` to an `Optional[Object]`, rather than an `Object`.

The case in question is [Mysql_server.sku](https://github.com/terraform-providers/terraform-provider-azurerm/blob/925050d82b9484f9d6ea02bf3ef481e8dd71339e/azurerm/resource_arm_mysql_server.go#L38-L40) (["azurerm_mysql_server"](https://github.com/terraform-providers/terraform-provider-azurerm/blob/c42a97019ae31e51f95dfc1c3ac0122917ae59ca/azurerm/provider.go#L339))

Which generates as 

```
    Mysql_server => {
      annotations => {
....
        }
      },
      attributes => {
.....
        'resource_group_name' => String,
        'sku' => Optional[Object[{
            attributes => {
              'capacity' => Integer,
              'family' => String,
              'name' => String,
              'tier' => String
            }
          }]],
....
      }
    },

```

(note `Optional[Object`)

So we end up with a runtime error instead of a validation error, even though terraform marks the type as mandatory.

**To Reproduce**
Run `make generate` and observe `build/types/AzureRM.pp` (to see the type definition)

Run a workflow with this action:

[https://github.com/ahpook/lyra-local/blob/90b646b723b33d7eee514478e729acbb17fa295b/workflows/azure_wordpress.yaml#L23-L30]()

**Expected behavior**
Validation that sku is mandatory, rather than attempt to apply the workflow.

**Logs**

<details>
  <summary>Runtime error</summary>

```sh
2019-05-15T10:50:16.723+0200 [ERROR] lyra: apply failed: Error="error while executing resource 'azure_wordpress::mysql_server' (file: workflows/azure_wordpress.yaml)
 at /Users/dimitri.tischenko/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190514150706-fc1fa286c815/wfe/workflowengine.go:492 (github.com/lyraproj/wfe/wfe.(*workflowEngine).runStepCatch.func1)
 at /usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:522 (runtime.call32)
 at /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 (runtime.gopanic)
 at /Users/dimitri.tischenko/go/pkg/mod/github.com/lyraproj/servicesdk@v0.0.0-20190514145959-5467213bbd8f/grpc/client.go:59 (github.com/lyraproj/servicesdk/grpc.(*Client).Invoke)
 at /Users/dimitri.tischenko/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190514150706-fc1fa286c815/service/crud.go:133 (github.com/lyraproj/wfe/service.ApplyState)
 at /Users/dimitri.tischenko/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190514150706-fc1fa286c815/wfe/resource.go:67 (github.com/lyraproj/wfe/wfe.(*resource).Run)
 at /Users/dimitri.tischenko/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190514150706-fc1fa286c815/wfe/workflowengine.go:527 (github.com/lyraproj/wfe/wfe.(*workflowEngine).runStepCatch)
 at /Users/dimitri.tischenko/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190514150706-fc1fa286c815/wfe/workflowengine.go:431 (github.com/lyraproj/wfe/wfe.(*workflowEngine).runStep)
 at /Users/dimitri.tischenko/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190514150706-fc1fa286c815/wfe/workflowengine.go:407 (github.com/lyraproj/wfe/wfe.(*workflowEngine).stepWorker)
 at /Users/dimitri.tischenko/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190514150706-fc1fa286c815/wfe/workflowengine.go:321 (github.com/lyraproj/wfe/wfe.(*workflowEngine).Run.func2)
 at /Users/dimitri.tischenko/go/pkg/mod/github.com/lyraproj/pcore@v0.0.0-20190514082225-61649d71c936/px/context.go:175 (github.com/lyraproj/pcore/px.Fork.func1)
Caused by: rpc error: code = Unknown desc = runtime error: index out of range (file: workflows/azure_wordpress.yaml)"
```

</details>
See https://gist.github.com/timidri/3cc99447ac588b3b2c9db4869034f6e6 for full log

**Environment (please complete the following information):**
- Latest

**Additional context**
<details>
  <summary>The full Mysql_server type</summary>

```
    Mysql_server => {
      annotations => {
        Lyra::Resource => {
          'providedAttributes' => ['mysql_server_id', 'fqdn', 'tags'],
          'immutableAttributes' => ['administrator_login', 'location', 'name', 'resource_group_name', 'version']
        }
      },
      attributes => {
        'mysql_server_id' => Optional[String],
        'administrator_login' => String,
        'administrator_login_password' => String,
        'fqdn' => Optional[String],
        'location' => String,
        'name' => String,
        'resource_group_name' => String,
        'sku' => Optional[Object[{
            attributes => {
              'capacity' => Integer,
              'family' => String,
              'name' => String,
              'tier' => String
            }
          }]],
        'ssl_enforcement' => String,
        'storage_profile' => Optional[Object[{
            attributes => {
              'backup_retention_days' => Optional[Integer],
              'geo_redundant_backup' => Optional[String],
              'storage_mb' => Integer
            }
          }]],
        'tags' => Optional[Hash[String, String]],
        'version' => String
      }
    },
```
</details>

**Comment by thallgren** [comment]
The terraform-bridge concludes that while the intermediate list is indeed required, it doesn't declare `MinItems: 1`  which means that it is permissible to provide a list with **zero or one** entry in it. The generation is therefore in accordance with the schema.

**Comment by markfuller** [comment]
Terraform does apply validation for this case.

```sh
➜  tfplanfun ls ../tfplanfun
mysql_azure.tf
➜  tfplanfun terraform apply

Error: azurerm_mysql_server.test: "sku": required field is not set


➜  tfplanfun
```

<details>
  <summary>mysql_azure.tf</summary>
```
resource "azurerm_resource_group" "test" {
  name     = "api-rg-pro"
  location = "West Europe"
}

resource "azurerm_mysql_server" "test" {
  name                = "mysql-server-1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

#   sku {
#     name     = "B_Gen5_2"
#     capacity = 2
#     tier     = "Basic"
#     family = "Gen5"
#     capacity = "2"
#  }

  storage_profile {
    storage_mb            = 5120
    backup_retention_days = 7
    geo_redundant_backup  = "Disabled"
  }

  administrator_login          = "mysqladminun"
  administrator_login_password = "H@Sh1CoR3!"
  version                      = "5.7"
  ssl_enforcement              = "Enabled"
}

```

[source](https://www.terraform.io/docs/providers/azurerm/r/mysql_server.html)
<details>

**Comment by thallgren** [comment]
I don't doubt that it's required in practice. I'm just stating that it isn't required in the schema, hence the generated optional. I'd consider this a schema bug (I bet there are many more similar inconsistencies).

One option is that we try to rectify such mistakes in our code, but I don't know how to find a good list or how to maintain it over time.

**Comment by markfuller** [comment]
I wonder if it as general issue such as _Terraform assumes a [Required List](https://github.com/terraform-providers/terraform-provider-azurerm/blob/925050d82b9484f9d6ea02bf3ef481e8dd71339e/azurerm/resource_arm_mysql_server.go#L38-L40) to mean a List of at least one item_.

**Comment by thallgren** [comment]
There are entries with both `Required: true` and `MinItems: 1` in the aws schema and there are them that lacks this definition. Examples: [aws/appmesh_route](https://github.com/terraform-providers/terraform-provider-aws/blob/53d74f10b44c3f28c3a427e195b18ac8447f5b29/aws/resource_aws_appmesh_route.go#L51-L54) and [azurerm/sku](https://github.com/terraform-providers/terraform-provider-azurerm/blob/c5a5017710a3a0d39f05001e2573d41d69166e6e/azurerm/resource_arm_mysql_server.go#L39-L41). We can of course treat them equal but it would be nice to get a confirmation that such a rule should be applied. The normal assumption would be that if you don't specify a constraint (like MinItems here), then it shouldn't apply.

**Comment by ahpook** [comment]
This is a great example of why I think it's better to integrate with the terraform runtime instead of the providers; we should be able to execute tf directly with an existing plan. IMO it's not worth spending the time to fix or avoid this problem.
