### ISSUE TITLE
lyra container should include cloud native CLI tools

### ISSUE THREAD

**Issue by kreeuwijk** [lyraproj/lyra#296]
The current lyra container lacks the CLI tools for AWS, Azure, GCP and K8s. This makes it harder for the user to configure the credentials to K8s and their clouds of choice. For Azure there is even no other way then using `az` to setup the connection. Please add these CLI tools to the image, and look at storing `~/` in a docker volume so that stored credentials can persist across container updates.

**Comment by timidri** [comment]
Alternatively, the lyra container could mount the various places with credentials from the host it's running on - no need for docker volumes.

**Comment by kreeuwijk** [comment]
Yes, but that assumes Lyra is used locally on a workstation that has these tools installed. When running Lyra as an operator in K8s for example, this would not be the case. Using a persistent volume for credentials would make this more portable and work better in a K8s cluster.

**Comment by timidri** [comment]
I see what you mean, that makes sense. In case of K8S docker volumes won't work so probably creating a helm chart for deploying a lyra operator into K8S is an option.

**Comment by kreeuwijk** [comment]
In K8s it would be a PV/PVC, which has the same result for the actual container (a volume gets mounted)
