### ISSUE TITLE
Publish json-schema for yaml syntax

### ISSUE THREAD

**Issue by ahpook** [lyraproj/lyra#303]
**Is your feature request related to a problem? Please describe.**
It's hard to know what valid maps/fields are in YAML workflows.

**Describe the solution you'd like**
It'd be beneficial to have a published json-scheme for the workflow syntax. One nice side effect of this is that the [redhat vscode yaml plugin](https://github.com/redhat-developer/vscode-yaml) will provide completion/validation for fields.

**Comment by thallgren** [comment]
@ahpook there's a PR up, lyraproj/yaml-workflow#4 that I'd like to get in before I start on #309.
