### ISSUE TITLE
Remove YAML "simplifications" in favor of a canonical syntax.

### ISSUE THREAD

**Issue by thallgren** [lyraproj/lyra#309]
I'm considering a couple of changes to the YAML format. I want a canonical way of writing things and avoid shortcuts/simplifications because that in turn improves code-completion suggestions when validating using a JSON-schema. It also makes the task of providing sane errors to guide the user when mistakes are made much easier.

1. A parameter should always be written as a key with an optional hash value. The current short form `<key>: <string>` where the string denotes a type is confusing. People tend to confuse that string with an actual value of the parameter. I.e. no more:
```
foo: Boolean
```
instead, always use
```
foo:
  type: Boolean
```
2. The current way of writing a resource, where we take advantage of the fact that a type name starts with a capital letter, is hard to validate and impossible to make a proper code completion suggestion for. So instead of:
```
Foobernetes::Instance:
  location: eu1
  image: lyra::database
```
I'd like us to declare the type and value explicitly::
```
resource: Foobernetes::Instance
value:
  location: eu1
  image: lyra::database
```
One could argue that `resource` here could be replaced with `type` but I'm leaning towards `resource` because this key is also identifying what kind of step this is, just like `steps` identifies a workflow step, or `call` identifies a call step.

Both changes described here are of course breaking changes.

**Comment by ahpook** [comment]
💯  I agree with both changes; if Puppet has taught me anything it's that explicit descriptions are better than implicit magic.

On the second one, `resource` is good; I would not want to use `type` there because it overloads the meaning based on context: as a workflow parameter it would mean data type, but inside a step it would mean resource type.  That seems very confusing.

**Comment by genebean** [comment]
Totally makes sense to me.
