### ISSUE TITLE
Discussion: Source of truth for existing infrastructure

### ISSUE THREAD

**Issue by dhollinger** [lyraproj/lyra#311]
**Is your feature request related to a problem? Please describe.**
As a user I want to be able to utilize Lyra on existing infrastructure without hassle or jumping through hoops to ensure a local state exists first.

**Describe the solution you'd like**
As a user I want Lyra to be able to apply state to existing infrastructure and treat the cloud infrastructure API response as the source of truth on a first run.

**Describe alternatives you've considered**
Leave existing functionality as is, but provide an option (configuration or CLI or both) to allow users to specify where they want their source of truth to exist

**Comment by thallgren** [comment]
Lyra doesn't dictate a "source of truth" today. There's a mapping from the internal ID (derived from the manifest) to the external ID that appoints a remote resource but the "source of truth" is always the external resource.

Can you provide a concrete example that explains what the effect of using the proposed CLI option would be?

**Comment by thallgren** [comment]
Closing this as no new info was provided.
