### ISSUE TITLE
Update README and keep it updated / introduce CHANGELOG

### ISSUE THREAD

**Issue by timidri** [lyraproj/lyra#315]
**Is your feature request related to a problem? Please describe.**
I noticed that the README is outdated.

**Describe the solution you'd like**
It would be helpful for novice users to have a simple and up to date README. The README should link to consumable documentation, including
* getting started with Lyra
* writing workflows
* writing Lyra plugins and actions

For users who already took a plunge, adding a CHANGELOG and keeping it updated would be of great help.

**Describe alternatives you've considered**
none

**Additional context**
Collaboration will be stimulated if using and extending Lyra is a straightforward and documented process.

**Comment by ahpook** [comment]
@hestonhoffman is working on docs - agree we need to keep the changelog updated, especially as there will be breaking changes until there's a 1.0
