### ISSUE TITLE
Add new "initializationAttributes" annotation

### ISSUE THREAD

**Issue by thallgren** [lyraproj/lyra#328]
Some attributes are solely intended for the initialization of a state and cannot be derived from the state with a subsequent read. Lyra must support such attributes. They are similar to immutable attributes in that a change should result in the recreation of the resource, but different in the sense that it is not possible to compare them to an actual value (the value is lost after creation of the resource).

The Heroku "Personal" attribute is a good example of the problem. The `OrganizationAppCreateOpts` struct used by the `OrganizationAppCreate` function contains the attribute (documented as "force creation of the app in the user account even if a default org"). A subsequent read using the function `OrganizationAppInfo` however, returns a `OrganizationApp` struct where the attribute is no longer available. It's not strange at all, given that the attribute is an instruction on how to proceed with some aspect of create.

One challenge here is that we cannot detect if the desired attribute found in the manifest matches what was used when the resource was created. There is no "source of truth" for this attribute. This leaves us with some alternatives:

1. We don't track the initialization attributes at all. I.e. if the user changes such an attribute in a manifest it will go undetected until the resource is recreated for other reasons than that change.
2. We track such attributes in the identity store together with the external ID. The disadvantage with that approach is that we introduce our own "source of truth".
3. We say that it is the resource handler's responsibility to track the attribute, which means that it instead introduces its own "source of truth" (in essence, this is just sticking our heads in the sand and ignore the whole thing as SEP).

My preference, given that none of the alternatives are ideal, is <span>#</span>1.

**Comment by thallgren** [comment]
One option that is viable is to make the external ID be a URL and then let the Create function that is responsible for creating that ID construct an URL where initialization attributes are included as URL parameters. That way, the attributes are forever attached to the created instance. Perhaps not the most intuitive way to do it, but it works.

**Comment by dhollinger** [comment]
We'd have to ensure that said URL is compatible with the upstream API client. Wouldn't want to have to rewrite an API client just to force it to work the way we want it to in Lyra.

**Comment by thallgren** [comment]
I don't see how anything but Lyra would ever see that URL. Look at the example I made in my PR to your PR: https://github.com/dhollinger/lyra/pull/1

**Comment by scottyw** [comment]
Our idea of using Terrform natively sounds related. In that case you again have a input to the step that cannot be read back - the Terraform files. It's not really the same situation as the Heroku creation attribute which presumably doesn't have any bearing on existing resources. I don't think we really answered the TF question yet and I wonder if that model, whatever it might be, might solve this case too?
