### ISSUE TITLE
Is this project dead? There havent been any commits in some time.

### ISSUE THREAD

**Issue by nmnellis** [lyraproj/lyra#347]
I was sent to check out this project from a friend but i see very little activity. If you have moved on, what other projects are you looking at?

**Comment by ahpook** [comment]
Hi @nmnellis - we are not developing the end-to-end Lyra workflow engine anymore. But there are a number of useful components from the project that are still under active development such as lyraproj/dgo and lyraproj/hiera 

We have shifted the workflow engine work to use tektoncd/pipelines and the front end to our [Nebula project](https://puppet.com/project-nebula)
