### ISSUE TITLE
AWS IAM resources 

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#40]
**Is your feature request related to a problem? Please describe.**
When I create new Kubernetes applications that require some AWS permissions (e.g. for logging for instance), I need to create or apply a new IAM role. I want to do that with a Lyra Workflow. 

**Describe the solution you'd like**
1. I can author a Workflow with declarative IAM role resources 
2. I can package that workflow up and reference it from my K8s Workflow CRD

**Describe alternatives you've considered**
None

**Additional context**
Something like this:

```
workflow "aws_iam_role" {
  typespace => 'aws',
} {
  resource IAM_role {
    assume_role_policy = <<EOF
     {
       "Version": "2012-10-17",
       "Statement": [
         {
           "Action": "sts:AssumeRole",
           "Principal": {
             "Service": "ec2.amazonaws.com"
           },
        "Effect": "Allow",
        "Sid": ""
         }
       ]
     }
     EOF
  }

  tags = {
      tag-key = "tag-value"
  }
}
```

**Comment by markfuller** [comment]
@kenazk this is merged, you wanna check it out and let me know if anything else is needed?

**Comment by kenazk** [comment]
Looks good to me.
