### ISSUE TITLE
Preview resources 

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#54]
**Is your feature request related to a problem? Please describe.**
Before applying a resource, I would like the **ability to preview** what will be created. 

- so that I don't spend £ I wasn't intending to on resources
- so that I see how my instantiation data affect the execution of the workflow
- so that I gain confidence in how Lyra works
- so that I can run the output of the preview through a testing framework to ensure it's been configured correctly
- so that I can get sign-off from other team members prior to provisioning

**Describe the solution you'd like**
Some sort of `lyra apply` pre-step or a separate `lyra preview` function that shows me resources that will be created as part of the Lyra apply. 

**Additional context**
Ideally, this should both be machine readable and human readable. It would be great to leverage an rspec-like testing framework to do assertion testing on the "catalog" or resulting resources that would be created.

**Comment by jdwelch** [comment]
What's the "so that" part? What exactly are you looking to learn with a preview?

**Comment by jdwelch** [comment]
Here's a few:
- 'so that I don't spend £ I wasn't intending to on resources'
- 'so that I see how my instantiation data affect the execution of the workflow'
- 'so that I gain confidence in how Lyra works'

Any big points I'm missing @kenazk?

**Comment by kenazk** [comment]
Oh yeah. Good catch @jdwelch. Here are a couple additional ones that I've heard so far: 

* So that I can run the output of the preview through a testing framework to ensure it's been configured correctly. 
* So that I can get sign-off from other team members prior to provisioning

**Comment by jdwelch** [comment]
👍

**Comment by kenazk** [comment]
@jdwelch Is this something prototype-able at this point? Or should I take a swing first?

**Comment by jdwelch** [comment]
https://www.lucidchart.com/publicSegments/view/4b44a50b-6b15-42cb-b005-11360046766c/image.png

**Comment by jdwelch** [comment]
Workflow: https://puppet.invisionapp.com/share/7XQAKKBV84Z#/screens/344376831

![preview](https://puppet.invisionapp.com/static-signed/live-embed/84676596/344429375/1/latest/etuWeMQvJ6cfx3RqiekHUyYbADkLBlE4mM8YN3CFFCOxU1ViUihwhJO6PEvQ5mWLZ9BoDW4M2wf7VFiqZuQ87wQlE/Apply-2x.png)
