### ISSUE TITLE
Leverage Terraform resource providers 

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#60]
**Is your feature request related to a problem? Please describe.**
I would really like a LOT more content for Lyra. Doing incremental content releases is good, but to prove out what Lyra can do, it needs a lot more content to be useful. 

**Describe the solution you'd like**
It would be really great if Lyra could leverage Terraform's resource providers. They already have a ton of content that would be awesome if we could use without re-inventing the wheel. 

**Additional context**
Prior art in this space:
* [Pulumi Terraform bridge](https://github.com/pulumi/pulumi-tf-provider-boilerplate)
* [CloudFormation bridge](https://github.com/iann0036/tf-cfn-provider)

**Comment by scottyw** [comment]
I think we have the core functionality here working. What do you think about closing this issue? There is probably an endless stream of work we can do in this area, like bridging more providers or fixing edge cases, but I think we can track that as individual issues.

**Comment by kenazk** [comment]
Sounds good 👍 @ahpook ?

**Comment by ahpook** [comment]
👍 i will make a new epic that has some specific high-value providers to add. could be a good starting point for new contributors
