### ISSUE TITLE
Try integrating additional Terraform providers

### ISSUE THREAD

**Issue by scottyw** [lyraproj/lyra#68]
The Terraform bridge prototype uses only the AWS provider.

Other providers can be found here: https://github.com/terraform-providers/

Initially we'll look at:
- [x] [Azure](https://github.com/terraform-providers/terraform-provider-azurerm)
- [x] [GCP](https://github.com/terraform-providers/terraform-provider-google)
- [x] [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes)
- [x] [GitHub](https://github.com/terraform-providers/terraform-provider-github)

**Comment by kenazk** [comment]
Sweeeeeet @scottyw. Here are a couple I would like to see: 
- [ ] [Azure](https://github.com/terraform-providers/terraform-provider-azurerm)
- [ ] [GCP](https://github.com/terraform-providers/terraform-provider-google)
- [ ] [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes)
- [ ] [GitHub](https://github.com/terraform-providers/terraform-provider-github)

**Comment by scottyw** [comment]
GitHub example here: https://github.com/lyraproj/lyra/blob/master/plugins/github_tf.yaml

**Comment by scottyw** [comment]
Google example in: https://github.com/lyraproj/lyra/tree/master/plugins
