### ISSUE TITLE
Produce consumable Lyra artefact

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#73]
Produce consumable Lyra artefact.

**USER STORIES:**
* I want to easily install and get started with Lyra so that I can quickly realize the value of Lyra.
* I want to execute Lyra Workflows with Lyra CLI so that I can see value and do basic operations without faffing around with K8s.

**Comment by jdwelch** [comment]
Dupe of #12 ?

**Comment by scottyw** [comment]
Bullet 2 is probably already true? Bullet 1 is arguably true - I can clone and make with just a couple of simple commands. If we're talking package managers we should maybe be more explicit about that.

**Comment by kenazk** [comment]
Yes, sorry this is dupe of #12. Will close this one.
