### ISSUE TITLE
Provider configuration 

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#79]
We need a better way to specify or override provider configuration. Right now, we pull the `~/.aws/config` for AWS configuration, but that should be the default, not the main way.

**Comment by jdwelch** [comment]
"so that"? Using the 'native' config is the most straightforward experience. What's the compelling reason to come up with a different system folks have to learn?

**Comment by kenazk** [comment]
So that I can specify an alternate region or set of credentials to the provider.

**Comment by scottyw** [comment]
In the near term we should make sure providers use one of the "out of band" way of getting config i.e. environment variables or well-know files. The AWS Terraform provider is an example of a hard-coded region and there's really no reason to do that.

In the longer term we should look at how we configure providers outside of workflows. @markfuller and I talked about maybe using a config file with a per-provider section that contains whatever the provider needs, that is specified on the command line at runtime.

Beyond even that we might want an additional means to bake provider config into workflows themselves e.g. workflowA runs in AWS region 1 while workflowB runs in AWS region 2. That brings a bunch of complexity so I'd favour leaving this level of granularity until we're sure we really need it.

**Comment by ahpook** [comment]
@jdwelch says
> "so that"? Using the 'native' config is the most straightforward experience. What's the compelling reason to come up with a different system folks have to learn?
To me this is the determinative question - and until there's an answer I don't think we need to solve for it.
