### ISSUE TITLE
Loadpath should support subdirs

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#80]
Today, loadpath only looks in plugins/ for Workflows. Lyra should support subdirectories so we can organize the plugin directory in some way. 

```
2019-01-25T13:29:47.584-0800 [DEBUG] lyra.loader: reading plugins from filesystem: dir=./plugins
...
[error] Unable to find definition for activity attachterraformyaml
```

Alongside our package format (#41), Lyra should load Workflows from subdirectories or well-known locations.

**Comment by thallgren** [comment]
I think we should consider letting subdirectories imply namespaces and file names imply name of the workflow they contain. I.e. a workflow named my::cool::stuff should reside in a file named "stuff.pp" under directory "workflows/my/cool". This would allow us to use a file based loader rooted under the "workflows" directory and load workflows on demand rather than pre-load everything at start-up like we do today.

**Comment by jdwelch** [comment]
Where's the "so that"; why is this feature important for an end-user? Why is this the right solution to whatever that problem is?

**Comment by kenazk** [comment]
Thanks @jdwelch for keeping us honest. The two key scenarios in my mind are: 

- As a producer of Workflows, I want Lyra to load workflows from a simple directory structure so that I can organize my Workflows in a simple, understandable way. 
- As a contributor to Lyra, I want Lyra to load workflows from a simple directory structure so that I know how and where to contribute code and other examples.

**Comment by thallgren** [comment]
I would like to add:

* As a producer of workflows, I want to reference one workflow from another using qualified names.
* As a producer of workflows, I want my workflow to be able to consume workflows provided by another producer.
* As a user of Lyra, I don't want cpu cycles, processes, and memory wasted loading workflows during startup unless I intend to apply them.

**Comment by jdwelch** [comment]
I'm +1 to the "workflows/my/cool" corresponds to "workflows::my::cool" pattern and am fine with going ahead and ticketing/implementing that solution.
