### ISSUE TITLE
Create a Helm plugin for Lyra 

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#88]
As a Helm user, I want Lyra to be available to me so that I can create Workflows and then use them as part of my Helm deployments. Helm plugins make it easy to install and run Lyra either locally or in Kubernetes.

**Comment by scottyw** [comment]
@ahpook What's your current thinking around this one? I'm not sure we're ready to move forward with it without some more thinking.

**Comment by ahpook** [comment]
This seems like the wrong way 'round to me; I'd expect to be able to run helm deployments as part of a workflow. It seems unlikely people would modify a bunch of helm charts to use Lyra, rather Lyra should be able to incorporate the large body of existing helm charts as "content" for use in a workflow.  

@kenazk does that make sense to you, or did I misunderstand the original request?

**Comment by kenazk** [comment]
Yeah, I agree. It was more from the perspective of existing Helm users getting leverage out of Lyra for the part of the deployment that they couldn't achieve with Helm. I think it's a minority use case, so happy to close this.
