### ISSUE TITLE
Improve workflow activity terminology.

### ISSUE THREAD

**Issue by thallgren** [lyraproj/lyra#90]
The current activity terminology is confusing. What's the difference between an "action" and a "stateless"? The current meaning of the terms are:

- "action" an activity that implements an interface with several functions.
- "stateless" an activity that acts as a function.

For "action", the only interface that is currently possible to implement is the "CRUD" interface used when operating on a resource state.

The term "action" is bad because it doesn't really describe what it currently means.
The term "stateless", added to be the opposite of "stateful" (which is a resource) isn't very clear either.

A couple of different suggestions have been made. Listed here in no particular order.

- Let "action" be CRUD, since that's what it really is. An implementation of a CRUD interface.
- Rename "resource" to "stateful" or perhaps simply "state" so that it matches "stateless".
- Rename "action" to "resource_provider" and then "stateless" to "action" (a.k.a. back to where we started).
- Rename "action" to "state_handler" and then "stateless" to "action".

We should probably avoid terms that are non-descriptive, have Puppet baggage, or are heavily overloaded.

**Comment by kenazk** [comment]
**Decision:** 
- "action" today will be renamed "state_handler" 
- "stateless" today will be renamed action
- "resource" is unchanged

**Comment by jdwelch** [comment]
Excellent. Thanks for humouring me :)
