### ISSUE TITLE
Add Lyra intermediate states to Kubernetes

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#94]
As a Lyra workflow consumer, I want to see how my Lyra workflow is progressing before trying to interact with it. I would really like to be able to see in kubernetes `kubectl get workflow attach-workflow` some more detailed status on whether the `apply` is completed or not.

**Comment by kenazk** [comment]
#95

**Comment by scottyw** [comment]
I really like this idea, I think we should definitely look into it.

@markfuller might interest you too.

**Comment by thallgren** [comment]
Perhaps there are two solutions to this? One that is k8s specific and one that is generic and based on a more competent distributed logging (or tracing). The latter relates to my comment on #95.

**Comment by markfuller** [comment]
Implemented.
```
➜  go-strcase git:(master) ✗ kubectl get workflows
NAME               WORKFLOWNAME      AGE   LYRASTATUS      STATUSINFO
sample2-workflow   sample2notreal   23h   RetryingApply   Unable to find definition for activity sample2notreal
```

See also my comment on #50
